
[deployables]

	[deployables.power_orbs]
		toggle_power_orb_expired_messages = false
		toggle_power_orb_tracker = true
		toggle_power_orb_timer = true
		alert_power_orb_expired_on_screen = true
		"â—_power_orb_expired_title_message" = "&dPower Orb Expired!"

	[deployables.flares]
		toggle_flare_timer = true
		toggle_flare_tracker = true
		toggle_flare_expired_messages = false
		"â—_flare_expired_title_message" = "&6Flare Expired!"
		alert_flare_expired_on_screen = true

	[deployables.all_deployables]
		toggle_deployable_sound = true
		"â—_deployable_expired_sound" = "mob.irongolem.death"
		"â—_deployable_sound_pitch" = 100
		deployable_chat_message = "([tableflip]) ([deployable]) Expired!"
		"â—_deployable_sound_volume" = 1.0
		hide_ui_if_not_present = false

	[deployables.corruption_totem]
		toggle_corruption_totem_timer = true
		toggle_corruption_totem_tracker = true
		"â—_totem_expired_title_message" = "&5Corruption Totem Expired!"
		alert_totem_expired_on_screen = true
		toggle_corruption_totem_expire_messages = false

[general_fishing]

	[general_fishing.other_settings]
		"hide_creature/dh_messages" = true
		count_worms_anyways = false
		hide_ui_if_not_relevant_-_general = false

	[general_fishing.creature_counting]
		"â—_creature_number_title_alert" = 60
		"â—_sea_creature_sound_volume" = 1.0
		"â—_sea_creature_number_sound" = 15
		alert_sea_creature_count_on_screen = true
		sea_creature_counter_ui = true
		toggle_sea_creature_count_sound = false
		toggle_sea_creature_counter = true
		sea_creatures_per_hour_ui = true
		toggle_sea_creature_party_messages = true
		"â—_sea_creature_sound_pitch" = 100
		"â—_sea_creature_party_message" = "Reached ([number]) sea creatures in ([time])"
		"â—_sea_creature_number_message_alert" = 60
		"â—_sea_creature_count_sound" = "random.orb"
		"â—_sea_creature_title_message_subtitle" = "&e([number]) sea creatures in ([time])!"
		"â—_sea_creature_title_message" = "&4&lKill Creatures!"
		"â—_sc/hr_time_to_reset" = 30

	[general_fishing.bobbin_features]
		toggle_bobber_counter_ui = true

	[general_fishing.double_hook]
		toggle_double_hook_messages = true
		"â—_double_hook_message" = "<Â°)))>< x2.|Woot Woot|Dubel Hook|à¸…^.ï»Œ.^à¸… ~ Double!|That'solotl Sea Creatures! ê’°Ë¶áµ”áµ•áµ”Ë¶ê’±|([dog]) ~ Woof Woof|Fish duping, shrimple as that ğŸ¤·"
		"â—_toggle_random_messages" = true

[pets]

	[pets.pet_level_up]
		toggle_pet_level_up_titles = true
		"â—_pet_level_title_message" = "&6&l([pet]) level ([level])"
		"â—_pet_level_title_alert" = 100

	[pets.pet_display]
		toggle_pet_display = true

[crimson_fishing]

	[crimson_fishing.boss_bar]
		"â—_toggle_plhlegblast_health_bar" = true
		"â—_boss_health_bar_length" = 300
		"â—_toggle_thunder_health_bar" = true
		"â—_toggle_jawbus_health_bar" = true
		toggle_boss_health_bar = true

	[crimson_fishing.fisherman_tracking]
		"â—_render_box_on_coords_on_warn" = true
		"â—_warn_sound_volume" = 0.1
		"â—_sound_on_warn" = true
		"â—_warn_upon_thunder_death" = false
		toggle_fisherman_tracking = false
		"â—_warn_upon_jawbus_death" = true
		"â—_player_coords_on_warn" = true
		"â—_warn_cooldown" = 60

	[crimson_fishing.mythic_creatures_lootsharing]
		"â—_thunder_lootshare_range" = false
		"â—_plhlegblast_lootshare_range" = true
		toggle_mythic_creature_lootshare_range = true
		"â—_jawbus_lootshare_range" = true

	[crimson_fishing.other_settings]
		hide_ui_if_not_relevant_-_crimson = false

	[crimson_fishing.mythic_creatures_ui]
		plhlegblast_ui = true
		thunder_ui = true
		jawbus_ui = true

	[crimson_fishing.vanquisher]
		vanquisher_ui = true
		toggle_vanquisher_party_messages = true
		"â—_vanquisher_message" = "Vanquisher (([number]) sc kills, ([time]))"

	[crimson_fishing.mythic_creatures_messages]
		"â—_plhlegblast" = "([hooray]) ([double])Plhlegblast (([number]) catches, ([time]))"
		"â—_thunder" = "([mixface]) ([double])Thunder (([number]) catches, ([time]))"
		toggle_mythic_creature_party_messages = true
		"â—_jawbus" = "([surprised]) ([double])Lord Jawbus (([number]) catches, ([time]))"

	[crimson_fishing.mythic_creatures_detection]
		"â—_mythic_creature_detection_title" = "&4&l([mob]) detected!"
		"â—_thunder_detection" = true
		"â—_mythic_detection_sound_volume" = 1.0
		"â—_plhlegblast_detection" = true
		"â—_jawbus_detection" = true
		toggle_mythic_creature_detection = true
		"â—_sound_on_detection" = true

[other]

	[other.detection_rate]
		crimson_bardetection_rate = 10
		crimson_fishing_detection_rate = 3
		general_fishing_detection_rate = 3

	[other.fun_messaging]
		add_characters_to_messages = "shrug,Â¯\\_(ãƒ„)_/Â¯|kiss,Ù©(*â›âŠ°â›)ï½â¤|flowersmile,(â—•â€¿â—•âœ¿)|disapointed,(ã†† _ ã††)|tableflip,(â•¯Â°oÂ°)â•¯ï¸µ â”»â”â”»|tablefliprage,(ãƒà² ç›Šà² )ãƒå½¡â”»â”â”»|eyes,(à² _à² )|dog,â–¼ãƒ»á´¥ãƒ»â–¼|hooray,\\ (â€¢â—¡â€¢) /|meh,(Â¬_Â¬)|mad,à² â•­â•®à² |wink,â—•â€¿â†¼|surprised,(â•¯Â°oÂ°)â•¯|mixface,â”Œ( à² _à² )â”˜"

	[other.death]
		"hide_ui_for_phoenix/spirit_mask_if_not_using" = false
		toggle_phoenix_pet_used_title = true
		phoenix_mask_status_ui = true
		toggle_spirit_mask_used_title = true
		spirit_mask_status_ui = true

	[other.chat]
		messages_chat = 3

	[other.fishing_rod_timer]
		"â—_rod_timer_ui_text" = " &e&l([time])|&c&lClick!"
		toggle_rendering_fishing_rod_timer_on_screen = true

	[other.title_times]
		title_duration = 40
		title_fade_out = 10
		title_fade_in = 10

	[other.other_settings]
		lobby_tracking = true

	[other.rendering]
		toggle_cool_item_rendering = true
		toggle_cool_item_rendering_background = true
		render_box_duration = 60
		toggle_chat_coords = true

[trophy_fishing]

	[trophy_fishing.sulphur_block]
		show_sulphur_range_on_right_click = true

	[trophy_fishing.other_settings]
		hide_ui_if_not_relevant_-_trophy_fishing = false

	[trophy_fishing.golden_fish]
		golden_fish_timer = true

[player_stats]

	[player_stats.mana]
		"â—_mana_percentage" = 0.19992395
		"â—_mana_low_title_message" = "&b&lMana low!"
		alert_when_mana_goes_below_a_percentage = true

[rare_drops]

	[rare_drops.radioactive_vial]
		toggle_radioactive_vial_message = true
		"â—_coop_chat" = false
		"â—_guild_chat" = true
		"â—_party_chat" = true
		toggle_radioactive_vial_ui = true
		"â—_vial_dropped_message" = "RARE DROP! Radioactive Vial (+([mf])% âœ¯ Magic Find (([number]) Jawbus Kills, ([time]))"
		"â—_all_chat" = true

	[rare_drops.other_drops]
		toggle_random_drops_message = true
		"â—_toggle_air_drop" = true

[crystal_hollows_fishing]

	[crystal_hollows_fishing.worm_fishing]
		"â—_worm_number_title_alert" = 60
		"â—_worm_number_sound" = 60
		"â—_worm_sound_volume" = 1.0
		toggle_worm_party_messages = false
		"â—_worm_number_message_alert" = 60
		"â—_worm_sound_pitch" = 100
		toggle_worm_counter = true
		hide_worm_nametag = false
		toggle_worm_count_sound = true
		"â—_worm_cap_title_message" = "&cWorm cap reached!"
		"â—_worm_sound" = "random.orb"
		alert_worm_count_on_screen = true
		"â—_worm_cap_title_message_subtitle" = "&c([number]) worms in ([time])!"
		"â—_worm_party_message" = "Worm cap reached! ([number]) worms in ([time])"

[chat_commands]

	[chat_commands.general_commands]
		command_prefix = "!"
		command_blacklist = ""
		command_cooldown = 1

	[chat_commands.info_commands]
		jawbusinfo = true
		thunderinfo = true
		vialinfo = true

	[chat_commands.party_commands]
		help = false
		transfer = false
		toggle_party_commands = true
		"warp_on_im_muted!" = true
		"â—_leader_only_new_member_help" = true
		new_member_help_command = false
		allinvite = false
		invite = false
		togglewarp = false
		coords = false
		warp = false

